// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function PromoteSuite(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteSuite'](arg1, arg2, arg3);
}

export function RunProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunProcess'](arg1, arg2, arg3);
}
