// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitPull(arg1:string):Promise<string>;

export function PromoteSuite(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunProcess(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;
