import path from 'node:path'
import type { Page } from '@playwright/test'
import { expect } from '@playwright/test'
import {
    beginProposal,
    chooseOrgAndCaptureId,
    fillProposal,
    generateStudyContent,
    openProposalDashboard,
    type StudyContent,
    submitProposal,
} from '../engine/flows/study'
import { repoDir } from '../engine/paths'
import type { RunContext, Suite } from './types'

// Traces the FULL study lifecycle end-to-end in one continuous run, switching
// between the researcher and reviewer accounts (via ctx.loginAs) at each gate:
//
//   researcher: create study
//   reviewer:   approve proposal
//   researcher: route to /code, launch IDE, upload code, submit
//   reviewer:   request code changes (round 1)
//   researcher: resubmit code (round 2 == the re-run: a fresh job)
//   reviewer:   approve code (round 2)
//   (qa runs the job) -> poll until results appear
//   reviewer:   decrypt + approve results
//   researcher: confirm results approved
//   reviewer:   (end here so teardown cleanup has delete authority)
//
// Selectors mirror management-app/tests/study-flow.spec.ts. The suite logs in as
// researcher first (roles/--role), then switches accounts itself.
//
// The IDE launch opens an external Coder workspace in a new window and is REQUIRED:
// the button must appear, the popup must open, and it must load, or the step fails.
//
// Requires the reviewer's results-decryption private key to approve results:
// set the Reviewer "Results private key" for the target env (qa/staging) in the
// Settings panel. The key is per-account AND per-env; env.ts resolves the one
// matching the running env (PR previews reuse qa) into ctx.resultsKey.

const RESEARCHER_ORG = 'openstax-lab'
const REVIEWER_ORG = 'openstax'
const CODE_CRITERIA_KEYS = [
    'proposalAlignment',
    'agreementCompliance',
    'securityChecks',
    'privacyProtection',
]

// How long to wait for the external enclave runner to produce results before
// giving up. The run happens outside the app (an editor service polls for
// approved jobs and POSTs encrypted results back), so this can take minutes.
const RESULTS_TIMEOUT_MS = 15 * 60_000
const RESULTS_POLL_INTERVAL_MS = 15_000
// Per-poll active-wait window: after each reload, wait this long for the results
// key box (or error) to actually render before deciding the results aren't ready
// yet. Covers the reload + SPA hydration so a not-yet-rendered box isn't missed.
const RESULTS_RENDER_WAIT_MS = 8_000
// The reviewer's decrypt input. The app renamed this placeholder from "Enter your
// Results Key to access encrypted content." to "Enter your security key", and QA,
// staging and PR previews run different builds — so match either wording, and only
// on the stable leading phrase rather than the trailing copy.
const RESULTS_KEY_PLACEHOLDER = /Enter your (security|results) key/i
// The button that submits that key. The app renamed it from "Decrypt Files" to
// "View", so — same reason as the placeholder above — match either wording. It
// must be scoped to the key's own card: once the files decrypt, every row of the
// file table gets its OWN "View" button, so an unscoped match is ambiguous.
const RESULTS_DECRYPT_BUTTON = /^(Decrypt Files|View)$/i
// The results file's row button in the decrypted "Output files" table. Anchored at
// the start so it matches that row's open control and NOT its "Download results.csv"
// sibling, and named so the log rows (security-scan-log.txt, …) can't match.
const RESULTS_FILE_BUTTON = /^results.*\.csv$/i
// Short settle after isReactHydrated before clicking the "Proceed to step 3"
// next/link button: the App Router route entry for the /agreements segment wires
// up just after initial hydration, and a click in that gap no-ops silently.
const PROCEED_NAV_SETTLE_MS = 500

// Shared per-run state threaded between steps via ctx.state. `study` is the
// generated content; `studyId` is captured in Step 1 (the moment the study record
// is created) and reused by every later step. Helpers read them off ctx.state.
function content(ctx: RunContext): StudyContent {
    return ctx.state.study as StudyContent
}
function id(ctx: RunContext): string {
    return ctx.state.studyId as string
}
// The reviewer's outputs-decision feedback. Read through a fallback because a RETRY
// after a suite edit re-runs the step against `ctx.state.study` generated by the
// OLD suite — so a content field added in that edit is genuinely absent mid-run, and
// passing undefined to keyboard.type fails the step for a reason that has nothing to
// do with the app under test.
function outputsFeedback(ctx: RunContext): string {
    return (
        content(ctx).resultsApprovalFeedback ||
        `Outputs reviewed, no sensitive or restricted data. (QA ${ctx.tag})`
    )
}

export const studyHappyPathSuite: Suite = {
    name: 'study-happy-path',
    description:
        'Full study lifecycle: create, upload, IDE, submit, review, resubmit, re-run, approve results',
    roles: ['researcher'],
    steps: [
        // ---- Researcher: create + submit the proposal (mirrors create-study) ----
        {
            name: 'Open the researcher org dashboard',
            run: async ctx => {
                // Realistic-but-clearly-synthetic study + review content (faker).
                // ctx.tag stays in the title so the row is findable and traceable.
                ctx.state.study = generateStudyContent(ctx.tag)
                await ctx.step(async () => {
                    await openProposalDashboard(ctx.page, ctx.baseURL)
                })
            },
        },
        {
            name: 'Start a new study proposal',
            run: ctx =>
                ctx.step(async () => {
                    await beginProposal(ctx.page)
                }),
        },
        {
            name: 'Step 1: choose org and language, then capture the study id',
            run: async ctx => {
                await ctx.step(async () => {
                    // Proceeding to Step 2 creates the study record. Capture + track
                    // its id the instant it exists, so no created study is untracked.
                    const studyId = await chooseOrgAndCaptureId(ctx.page)
                    ctx.state.studyId = studyId
                    ctx.trackStudy(studyId)
                })
            },
        },
        {
            name: 'Step 2: fill the proposal',
            run: ctx =>
                ctx.step(async () => {
                    await fillProposal(ctx.page, content(ctx))
                }),
        },
        {
            name: 'Submit the initial request',
            run: ctx =>
                ctx.step(async () => {
                    await submitProposal(ctx.page)
                }),
        },
        // ---- Reviewer: approve the proposal (gates the code-upload surface) ----
        {
            name: 'Switch to the reviewer account',
            run: ctx => ctx.step(() => ctx.loginAs('reviewer')),
        },
        {
            name: 'Reviewer approves the proposal',
            run: ctx =>
                ctx.step(async () => {
                    await gotoReview(ctx, id(ctx))
                    const feedback = ctx.page
                        .getByTestId('review-feedback-section')
                        .locator('[contenteditable="true"]')
                    await feedback.click()
                    await ctx.page.keyboard.type(content(ctx).proposalFeedback)
                    await ctx.page
                        .getByTestId('review-decision-section')
                        .getByRole('radio', { name: /^Approve$/i })
                        .check()
                    await ctx.page.getByRole('button', { name: /^Submit review$/i }).click()
                    await confirmDialog(ctx, /^Yes, submit review$/i)
                    await ctx.page.getByText(/Approved on/).waitFor({ state: 'visible' })
                }),
        },
        // ---- Researcher: route to code upload, launch IDE, upload + submit ----
        {
            name: 'Switch back to the researcher account',
            run: ctx => ctx.step(() => ctx.loginAs('researcher')),
        },
        {
            name: 'Route to the code upload page',
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.goto(
                        `${ctx.baseURL}/${RESEARCHER_ORG}/study/${id(ctx)}/submitted`,
                        {
                            waitUntil: 'domcontentloaded',
                        }
                    )
                    // Advance step-by-step, waiting for a distinctive element on each
                    // destination page: clicking "Proceed to step 3" lands on the agreements
                    // page, whose own "Proceed to Step 4" button is the arrival signal;
                    // clicking that lands on /code, signalled by "Upload your files".
                    //
                    // The "Proceed to step 3" anchor is server-rendered, so it is visible
                    // (and click-actionable) before the SPA finishes hydrating — a click that
                    // lands in that window is swallowed by the not-yet-mounted router and the
                    // page stays on /submitted. Wait for the app's hydration flag before the
                    // single click; a click on the hydrated page navigates reliably, so if it
                    // then fails to advance that is a real app bug this step should surface.
                    // Tight timeout on purpose: a healthy page hydrates in ~1s, so if the
                    // flag isn't set within a few seconds that is a real slow-hydration
                    // problem we want surfaced, not absorbed by the 30s default.
                    await ctx.page.waitForFunction(
                        () => (window as { isReactHydrated?: boolean }).isReactHydrated === true,
                        undefined,
                        { timeout: 5_000 }
                    )
                    // "Proceed to step 3" is a Mantine <Button component={next/link}>: its
                    // onClick preventDefaults the native anchor navigation and relies on the
                    // App Router's router.push. isReactHydrated flips true at initial
                    // hydration, but the client route entry for the /agreements segment wires
                    // up slightly later — a click in that gap is consumed while router.push
                    // no-ops, so the page silently stays on /submitted (no error). There's no
                    // exposed "route ready" signal to await, so settle briefly after
                    // hydration before the single click.
                    const proceedToStep3 = ctx.page.getByRole('link', {
                        name: /Proceed to step 3/i,
                    })
                    await proceedToStep3.waitFor({ state: 'visible' })
                    await ctx.page.waitForTimeout(PROCEED_NAV_SETTLE_MS)
                    await proceedToStep3.click()
                    const proceedToStep4 = ctx.page.getByRole('button', {
                        name: /Proceed to Step 4/i,
                    })
                    await proceedToStep4.waitFor({ state: 'visible' })
                    await proceedToStep4.click()
                    await ctx.page.getByText('Upload your files').waitFor({ state: 'visible' })
                }),
        },
        {
            name: 'Launch the IDE',
            // Click "Edit files in IDE" and require the external Coder IDE to open and
            // load the code-server workspace. The button is an anchor that normally
            // opens Coder in a NEW TAB (target=_blank). Under CDP-attached Chrome that
            // new tab does not reliably surface as a `page` event on ctx.page's context,
            // so waiting for one hangs. Instead we CTRL/CMD-CLICK (Shift here), which
            // suppresses target=_blank and forces the navigation to happen in the SAME
            // tab (ctx.page). The button must be present, the workspace must provision
            // and navigate here, its "Continue to launch IDE" OIDC re-auth + Clerk
            // sign-in must complete, and the code-server workbench must actually render.
            // Any of these failing FAILS the step — the IDE launch is part of the
            // researcher lifecycle we assert, not a best-effort nicety.
            run: ctx =>
                ctx.step(async () => {
                    const btn = ctx.page
                        .getByRole('button', { name: /Launch IDE|Edit files in IDE/i })
                        .first()
                    // A RETRY re-runs this step against the SAME live browser, parked
                    // wherever the failed attempt left it — for this step that is the
                    // Coder IDE tab, where this button does not exist. Without
                    // re-anchoring, every retry times out on a page that was never the
                    // subject, hiding the real cause (the IDE not loading). Gate the
                    // re-navigation on the BUTTON, not on a page-state marker: /code
                    // renders an "Upload your files" empty state before any file exists
                    // and a "Review files" table once the workspace has seeded them, so
                    // the button is the only signal stable across both. No-op on the
                    // normal path — the previous step already landed here.
                    if (!(await btn.isVisible().catch(() => false))) {
                        await ctx.page.goto(
                            `${ctx.baseURL}/${RESEARCHER_ORG}/study/${id(ctx)}/code`,
                            { waitUntil: 'domcontentloaded' }
                        )
                    }
                    await btn.waitFor({ state: 'visible' })
                    // On a cold workspace the app provisions the whole code-server
                    // environment FIRST ("Launching IDE" + a progress bar) and only then
                    // navigates. Ctrl/Cmd-click keeps that navigation in THIS tab. We
                    // don't wait on a Coder URL — the destination markers below (the
                    // "Continue to launch IDE" control or the workbench) are the real
                    // proof of arrival, and provisioning can take minutes.
                    await btn.click({ modifiers: ['Shift'] })
                    // Coder's OIDC uses prompt=login, so launching lands on Coder's
                    // "session expired / Continue to launch IDE" page — a LINK (not a
                    // button) to the OIDC callback — even though the app session is live.
                    // Follow it, which redirects through Clerk's hosted sign-in. On a warm
                    // session it may skip straight to the workbench, so only click Continue
                    // if it renders.
                    const continueControl = ctx.page
                        .getByRole('link', { name: /Continue to launch IDE/i })
                        .or(ctx.page.getByRole('button', { name: /Continue to launch IDE/i }))
                    const workbench = ctx.page.locator('.monaco-workbench')
                    // Cold-workspace provisioning can take minutes; this race (not a
                    // URL wait) is now the arrival gate, so give it the full budget.
                    const seen = await Promise.race([
                        continueControl
                            .first()
                            .waitFor({ state: 'visible', timeout: 300_000 })
                            .then(() => 'continue')
                            .catch(() => null),
                        workbench
                            .first()
                            .waitFor({ state: 'visible', timeout: 300_000 })
                            .then(() => 'workbench')
                            .catch(() => null),
                    ])
                    if (seen === 'continue') {
                        await continueControl.first().click()
                    }
                    // Complete Coder's Clerk-hosted OIDC sign-in as the current role (no-op
                    // if the workbench is already up), then require the code-server
                    // workbench to actually render — a Coder URL alone isn't proof the IDE
                    // loaded.
                    await signInToCoder(ctx, ctx.page)
                    await workbench.first().waitFor({ state: 'visible', timeout: 300_000 })
                    // The IDE is left OPEN on ctx.page; a later step navigates back to /code.
                }),
        },
        {
            name: 'Run main.r in the IDE',
            // Run main.R inside the open code-server IDE: open the file from the
            // Explorer, click the editor toolbar's "Run Source" action, then prove it
            // produced output by opening the generated results.csv and asserting it
            // contains a numeric value.
            //   - The Explorer shows the file as `main.R`; the toolbar action is an
            //     <a role=button> with aria-label "Run Source (⇧⌘S)".
            //   - Sourcing runs the file in an "R Interactive" terminal and writes
            //     results.csv to the workspace root (via write.csv). The Explorer doesn't
            //     auto-refresh for files the extension writes, so we click "Refresh
            //     Explorer" and poll until it appears.
            //   - Opening results.csv renders its rows as Monaco `.view-line`s; we require
            //     at least one line to contain a digit (the sample writes a header plus a
            //     count, e.g. 345).
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.getByRole('treeitem', { name: 'main.R' }).click()
                    await ctx.page
                        .getByRole('tab', { name: /main\.R/i })
                        .waitFor({ state: 'visible' })
                    await ctx.page.getByRole('button', { name: /Run Source/i }).click()
                    // Sourcing spins up (or reuses) the R Interactive terminal; require it.
                    await ctx.page.getByText('R Interactive').first().waitFor({ state: 'visible' })

                    const resultsFile = ctx.page.getByRole('treeitem', { name: 'results.csv' })
                    await expect(async () => {
                        await ctx.page.getByRole('button', { name: 'Refresh Explorer' }).click()
                        await expect(resultsFile).toBeVisible()
                    }).toPass()

                    await resultsFile.click()
                    await ctx.page
                        .getByRole('tab', { name: /results\.csv/i })
                        .waitFor({ state: 'visible' })
                    // Monaco renders each CSV row as a .view-line; require a numeric value.
                    const numericRow = ctx.page
                        .locator('.view-lines .view-line')
                        .filter({ hasText: /\d/ })
                    await expect(numericRow.first()).toBeVisible()
                }),
        },
        {
            name: 'Return to the code upload page',
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.goto(`${ctx.baseURL}/${RESEARCHER_ORG}/study/${id(ctx)}/code`, {
                        waitUntil: 'domcontentloaded',
                    })
                    // Files already exist (uploaded via the IDE run), so the page renders the
                    // "Review files" management view rather than the empty-state "Upload your
                    // files" prompt. The "Study code" heading anchors both states.
                    await ctx.page
                        .getByRole('heading', { name: 'Study code' })
                        .waitFor({ state: 'visible' })
                }),
        },
        {
            name: 'Upload the study code (round 1)',
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.locator('input[type="file"]').setInputFiles(fixtureFiles())
                    await ctx.page
                        .getByRole('cell', { name: 'main.r', exact: true })
                        .waitFor({ state: 'visible' })
                    await ctx.page
                        .getByRole('cell', { name: 'code.r', exact: true })
                        .waitFor({ state: 'visible' })
                }),
        },
        {
            name: 'Submit the study code (round 1)',
            run: ctx =>
                ctx.step(async () => {
                    // The fixed AppShell footer intercepts pointer events on the button.
                    await ctx.page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
                    await ctx.page.getByRole('button', { name: /Submit code/i }).click()
                    await ctx.page.getByRole('button', { name: 'Yes, submit study code' }).click()
                    // Code submission redirects to CodePostSubmissionView; wait on its banner.
                    await ctx.page
                        .getByTestId('code-under-review-banner')
                        .waitFor({ state: 'visible' })
                }),
        },
        // ---- Reviewer: request code changes (round 1) ----
        {
            name: 'Switch to the reviewer account',
            run: ctx => ctx.step(() => ctx.loginAs('reviewer')),
        },
        {
            name: 'Reviewer requests code changes',
            run: ctx =>
                ctx.step(async () => {
                    await openCodeReview(ctx, id(ctx))
                    await setCodeCriteria(ctx, 'no')
                    await ctx.page.getByTestId('code-review-decision-needs-clarification').click()
                    await typeCodeFeedback(ctx, content(ctx).changeRequestFeedback)
                    await submitCodeReview(ctx, /Change requested on/)
                }),
        },
        // ---- Researcher: resubmit code (round 2 == the re-run) ----
        {
            name: 'Switch back to the researcher account',
            run: ctx => ctx.step(() => ctx.loginAs('researcher')),
        },
        {
            name: 'Resubmit the study code (round 2 / re-run)',
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.goto(
                        `${ctx.baseURL}/${RESEARCHER_ORG}/study/${id(ctx)}/resubmit`,
                        {
                            waitUntil: 'domcontentloaded',
                        }
                    )
                    await ctx.page
                        .getByRole('heading', { name: /Edit study code/i })
                        .waitFor({ state: 'visible' })
                    await ctx.page.locator('input[type="file"]').setInputFiles(fixtureFiles())
                    await ctx.page
                        .getByLabel(/Resubmission Note/i)
                        .fill(content(ctx).resubmissionNote)
                    // The fixed AppShell footer intercepts pointer events on the button.
                    await ctx.page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
                    await ctx.page.getByRole('button', { name: /^Resubmit study code$/i }).click()
                    await ctx.page
                        .getByRole('button', { name: /^Yes, resubmit study code$/i })
                        .click()
                    // Resubmit lands on the study view; the "Edit study code" heading
                    // is gone once submitted, so wait for that heading to detach as the
                    // signal the resubmit navigated away from the edit form.
                    await ctx.page
                        .getByRole('heading', { name: /Edit study code/i })
                        .waitFor({ state: 'hidden' })
                }),
        },
        // ---- Reviewer: approve code (round 2) ----
        {
            name: 'Switch to the reviewer account',
            run: ctx => ctx.step(() => ctx.loginAs('reviewer')),
        },
        {
            name: 'Reviewer approves the code',
            run: ctx =>
                ctx.step(async () => {
                    await openCodeReview(ctx, id(ctx))
                    await setCodeCriteria(ctx, 'yes')
                    await ctx.page.getByTestId('code-review-decision-approve').click()
                    await typeCodeFeedback(ctx, content(ctx).codeApprovalFeedback)
                    await submitCodeReview(ctx, /Approved on/)
                }),
        },
        // ---- qa runs the job; wait for results, then decrypt + approve ----
        {
            name: 'Wait for the run to complete and produce results',
            run: ctx => ctx.step(() => waitForResults(ctx, id(ctx))),
        },
        {
            name: 'Reviewer decrypts and views the results',
            run: ctx =>
                ctx.step(async () => {
                    const key = ctx.resultsKey
                    if (!key) {
                        throw new Error(
                            'Missing reviewer results key for this environment: set the Reviewer "Results private key" ' +
                                'for this env (qa/staging) in the Settings panel.'
                        )
                    }
                    // Decrypting REMOVES the key box from the page, so this step is not
                    // re-enterable against a page that already decrypted (a retry, or a
                    // reload of a page a previous attempt got through). Decrypt only
                    // when the box is actually there; otherwise fall through to the
                    // already-decrypted file table below.
                    const keyBox = ctx.page.getByPlaceholder(RESULTS_KEY_PLACEHOLDER)
                    if (await keyBox.isVisible().catch(() => false)) {
                        await keyBox.fill(key)
                        const keyCard = ctx.page
                            .locator('.mantine-Paper-root')
                            .filter({ has: keyBox })
                        await keyCard.getByRole('button', { name: RESULTS_DECRYPT_BUTTON }).click()
                    }
                    // Open the RESULTS file's preview — NOT a log — and confirm it actually
                    // rendered the decrypted output, not merely that a control exists. In the
                    // "Output files" table each row's open control is a button NAMED AFTER
                    // ITS FILE (there is no generic "View" action, and no file-type column),
                    // so select the results file by name and leave the log rows alone.
                    const openResults = ctx.page
                        .getByTestId('outputs-files-table')
                        .getByRole('button', { name: RESULTS_FILE_BUTTON })
                    await openResults.waitFor({ state: 'visible', timeout: 20_000 })
                    await openResults.click()
                    // Assert the open results-preview modal actually rendered the decrypted
                    // output. The results file is a CSV, previewed as a mantine-datatable
                    // grid whose rows the app builds from the CSV — so a successful decrypt
                    // shows data rows, while a decrypt-but-empty/garbled result shows a
                    // header-only (or empty) grid. Wait for a populated data row and confirm
                    // it carries content, rather than a specific value so it survives
                    // run-to-run data changes.
                    const dialog = ctx.page.getByRole('dialog')
                    await dialog.waitFor({ state: 'visible', timeout: 20_000 })
                    const firstRow = dialog.locator('table tbody tr').first()
                    await firstRow.waitFor({ state: 'visible', timeout: 15_000 })
                    const text = (await firstRow.innerText())?.trim() ?? ''
                    if (!text) {
                        const modalText = (await dialog.innerText())?.slice(0, 500) ?? ''
                        throw new Error(
                            `Results preview modal rendered an empty grid row. Modal text:\n${modalText}`
                        )
                    }
                    // Close the preview so it doesn't overlay the Approve button.
                    // The Mantine modal's close control is an icon-only CloseButton
                    // with no accessible name (no aria-label/title/text), so a
                    // name-based role locator can't find it — target the stable
                    // Mantine class instead, and fall back to Escape.
                    const closeButton = dialog.locator('.mantine-Modal-close')
                    if (await closeButton.count()) {
                        await closeButton.first().click()
                    } else {
                        await ctx.page.keyboard.press('Escape')
                    }
                    await dialog.waitFor({ state: 'hidden' }).catch(() => {})
                }),
        },
        {
            name: 'Reviewer approves the results',
            run: ctx =>
                ctx.step(async () => {
                    // Approving outputs is no longer a bare "Approve" button: the reviewer
                    // states a decision (share the outputs, vs. share only the feedback —
                    // the latter is the WITHHOLD path, so the happy path picks the former),
                    // writes required feedback, and submits.
                    //
                    // Submitting REPLACES the decision form with the confirmation banner,
                    // so this step is not re-enterable against a page that already
                    // submitted (a retry, or a reload of a page a previous attempt got
                    // through). Submit only when the form is actually there; otherwise
                    // fall through to the banner assertion below.
                    const decisionForm = ctx.page.getByTestId('outputs-decision-section')
                    if (await decisionForm.isVisible().catch(() => false)) {
                        await typeOutputsFeedback(ctx, outputsFeedback(ctx))
                        await ctx.page.getByTestId('outputs-decision-share-outputs').check()
                        await ctx.page.getByTestId('outputs-submit-decision').click()
                        // Submitting opens a "Submit your decision?" confirm. Its button
                        // repeats the page's own name ("Submit decision") rather than the
                        // code review's "Yes, submit review" — confirmDialog scopes the
                        // match to the dialog, so the repeated name is unambiguous.
                        await confirmDialog(ctx, /^Submit decision$/i)
                    }
                    // Sharing the outputs does NOT navigate anywhere: the review page
                    // stays put and swaps the decision form for this status banner. (It
                    // used to be asserted via the reviewer dashboard's "Review Studies"
                    // heading, which no longer appears because there is no redirect.)
                    await expect(ctx.page.getByTestId('status-alert')).toContainText(
                        /Outputs and feedback shared/i
                    )
                }),
        },
        // ---- Researcher: confirm the approved results are visible ----
        {
            name: 'Switch back to the researcher account',
            run: ctx => ctx.step(() => ctx.loginAs('researcher')),
        },
        {
            name: 'Researcher sees the approved results',
            run: ctx =>
                ctx.step(async () => {
                    await ctx.page.goto(`${ctx.baseURL}/${RESEARCHER_ORG}/study/${id(ctx)}/view`, {
                        waitUntil: 'domcontentloaded',
                    })
                    await ctx.page
                        .getByText(/results of your study have been approved/i)
                        .waitFor({ state: 'visible' })
                }),
        },
        {
            name: 'Switch to the admin account for cleanup authority',
            // End as admin so guaranteed teardown cleanup runs with delete
            // authority: the /api/qa DELETE endpoints require isSiAdmin, which the
            // researcher and reviewer accounts lack (a reviewer-session cleanup 401s).
            run: ctx => ctx.step(() => ctx.loginAs('admin')),
        },
        {
            name: 'Verify the study is deleted',
            // Delete the study via the QA cleanup API and ASSERT it succeeded, so a
            // cleanup failure fails the run loudly instead of being swallowed by the
            // engine's best-effort teardown (which folds a failed delete into a
            // non-fatal 'cleanup' category). The engine's later teardown delete of
            // the same id then harmlessly 404s.
            run: ctx =>
                ctx.step(async () => {
                    await deleteStudyAndVerify(ctx, id(ctx))
                }),
        },
    ],
}

// Delete a study through the QA cleanup API using the admin's Clerk session token
// (read from the page), assert a 2xx, then confirm a repeat delete reports it gone
// (404). Throws on anything else so cleanup problems surface as a failed step.
async function deleteStudyAndVerify(ctx: RunContext, studyId: string): Promise<void> {
    const token = await ctx.page.evaluate(async () => {
        const clerk = (
            window as unknown as {
                Clerk?: { session?: { getToken(): Promise<string | null> } }
            }
        ).Clerk
        return (await clerk?.session?.getToken()) ?? ''
    })
    if (!token) throw new Error('Could not read admin Clerk token to verify study cleanup')

    const del = () =>
        ctx.page.request.delete(`${ctx.baseURL}/api/qa/studies/${studyId}`, {
            headers: { Authorization: `Bearer ${token}` },
        })

    const res = await del()
    if (!res.ok()) {
        throw new Error(`QA cleanup DELETE study ${studyId} failed: HTTP ${res.status()}`)
    }
    // Confirm it's actually gone: a second delete finds nothing (404).
    const again = await del()
    if (again.status() !== 404) {
        throw new Error(
            `Study ${studyId} still present after delete (repeat DELETE returned ${again.status()}, expected 404)`
        )
    }
}

// --- helpers (mirror management-app/tests/study-flow.spec.ts) ---
// StudyContent, generateStudyContent, and fillLexical now live in
// ../engine/flows/study (shared with ad-hoc validation suites).

// The two code files the app accepts, resolved against the cloned repo (NOT the
// engine bundle location) via repoDir(), which honors QAR_REPO_DIR at runtime.
// (import.meta.url-relative paths would point at the bundle, not the clone.)
function fixtureFiles(): string[] {
    const dir = path.join(repoDir(), 'src', 'suites', 'fixtures', 'study-happy-path')
    return [path.join(dir, 'main.r'), path.join(dir, 'code.r')]
}

async function gotoReview(ctx: RunContext, studyId: string): Promise<void> {
    await ctx.page.goto(`${ctx.baseURL}/${REVIEWER_ORG}/study/${studyId}/review`, {
        waitUntil: 'domcontentloaded',
    })
}

// Confirm in the modal and wait for it to close. On the live preview the confirm
// click can land before the dialog's handler is wired, leaving it open — retry
// the click until the dialog hides.
async function confirmDialog(ctx: RunContext, confirmName: RegExp): Promise<void> {
    const dialog = ctx.page.getByRole('dialog')
    await dialog.waitFor({ state: 'visible' })
    for (let attempt = 0; attempt < 3; attempt++) {
        await dialog
            .getByRole('button', { name: confirmName })
            .click()
            .catch(() => {})
        const hidden = await dialog
            .waitFor({ state: 'hidden', timeout: 20_000 })
            .then(() => true)
            .catch(() => false)
        if (hidden) return
    }
    // Surface the real error if it genuinely never closed.
    await dialog.waitFor({ state: 'hidden', timeout: 10_000 })
}

// Reach the code-review editor. When the reviewer hasn't acked the agreements, an
// agreements gate (STEP 2A/2B/2C) renders first and its "Proceed to Step 3" button
// advances to the code-review editor. On the live preview that gate can take a
// moment to hydrate, so poll: each round, if the code-review section is up we're
// done; else click "Proceed to Step 3" if present and wait.
async function openCodeReview(ctx: RunContext, studyId: string): Promise<void> {
    const section = ctx.page.getByTestId('code-review-section')
    const proceed = ctx.page.getByRole('button', { name: /Proceed to Step 3/i })
    for (let attempt = 0; attempt < 4; attempt++) {
        await gotoReview(ctx, studyId)
        // Either the editor renders directly, or the agreements gate does — wait
        // for whichever appears first before deciding.
        await Promise.race([
            section.waitFor({ state: 'visible', timeout: 20_000 }).catch(() => {}),
            proceed.waitFor({ state: 'visible', timeout: 20_000 }).catch(() => {}),
        ])
        if (await section.isVisible().catch(() => false)) return
        if (await proceed.isVisible().catch(() => false)) {
            await proceed.click().catch(() => {})
            if (
                await section
                    .waitFor({ state: 'visible', timeout: 20_000 })
                    .then(() => true)
                    .catch(() => false)
            ) {
                return
            }
        }
    }
    // Final wait so a genuine failure surfaces the real timeout error.
    await section.waitFor({ state: 'visible', timeout: 15_000 })
}

async function setCodeCriteria(ctx: RunContext, value: 'yes' | 'no'): Promise<void> {
    for (const key of CODE_CRITERIA_KEYS) {
        await ctx.page.locator(`input[name="criteria-${key}"][value="${value}"]`).check()
    }
}

async function typeCodeFeedback(ctx: RunContext, text: string): Promise<void> {
    const feedback = ctx.page
        .getByTestId('code-review-section')
        .locator('[contenteditable="true"]')
        .first()
    await feedback.click()
    await ctx.page.keyboard.type(text)
}

// The outputs-decision feedback field, same shape as the code-review one: a Lexical
// contenteditable that needs a REAL click to place the caret before typing (focusing
// it programmatically leaves no caret and the typed text goes nowhere).
async function typeOutputsFeedback(ctx: RunContext, text: string): Promise<void> {
    const feedback = ctx.page
        .getByTestId('outputs-decision-section')
        .locator('[contenteditable="true"]')
        .first()
    await feedback.click()
    // Replace rather than append: a retry re-enters this step against a form the
    // previous attempt already typed into, and the field has a word limit.
    await ctx.page.keyboard.press('ControlOrMeta+A')
    await ctx.page.keyboard.type(text)
}

async function submitCodeReview(ctx: RunContext, doneRegex: RegExp): Promise<void> {
    await ctx.page.getByTestId('code-review-submit').click()
    await confirmDialog(ctx, /^Yes, submit review$/i)
    await ctx.page.getByText(doneRegex).waitFor({ state: 'visible' })
}

// Complete Coder's Clerk-hosted OIDC sign-in as the current role, on the IDE popup
// page. Coder uses prompt=login, so launching the IDE always lands on Clerk's hosted
// sign-in (accounts.dev) — a DIFFERENT form from the app's embedded one (auth.ts):
// it's the staged flow email -> Continue -> password -> Continue -> SMS MFA code.
// Uses ctx.account (the currently signed-in role's creds), so the secret is typed by
// the engine, never surfaced. No-ops if the workbench is already up (warm session
// that skipped the login). A missing expected control FAILS the step.
async function signInToCoder(ctx: RunContext, ide: Page): Promise<void> {
    const workbench = ide.locator('.monaco-workbench')
    const emailField = ide.getByLabel(/Email address/i)
    // Either the IDE is already loaded (no login needed) or the Clerk email step is
    // up. Wait for whichever appears before deciding.
    await Promise.race([
        workbench
            .first()
            .waitFor({ state: 'visible', timeout: 60_000 })
            .catch(() => {}),
        emailField
            .first()
            .waitFor({ state: 'visible', timeout: 60_000 })
            .catch(() => {}),
    ])
    if (
        await workbench
            .first()
            .isVisible()
            .catch(() => false)
    )
        return
    if (
        !(await emailField
            .first()
            .isVisible()
            .catch(() => false))
    ) {
        throw new Error(
            `IDE did not open: expected the Coder/Clerk sign-in or the code-server ` +
                `workbench, but neither rendered. URL: ${ide.url()}`
        )
    }
    // Email -> Continue.
    await emailField.first().fill(ctx.account.email)
    await ide.getByRole('button', { name: /^Continue$/i }).click()
    // Password -> Continue. Clerk labels the field "Password"; the primary button is
    // "Continue" on the hosted flow.
    const passwordField = ide.getByLabel(/^Password$/i)
    await passwordField.waitFor({ state: 'visible', timeout: 60_000 })
    await passwordField.fill(ctx.account.password)
    await ide.getByRole('button', { name: /^Continue$/i }).click()
    // SMS MFA: the same fixed second-factor code the app login uses. Clerk renders a
    // one-time-code input (a row of single-char boxes or one combined field); fill it
    // and, if a submit button is shown rather than auto-advancing, click it.
    await fillCoderMfa(ide, ctx.account.mfaCode)
    // The verified login redirects back to Coder; the workbench assertion in the
    // caller confirms code-server actually rendered.
}

// Enter the SMS MFA code on Clerk's hosted verification step, on the IDE popup page.
// The code input is a segmented OTP field: try the per-digit inputs first, else a
// single combined field.
async function fillCoderMfa(ide: Page, code: string): Promise<void> {
    const otpInputs = ide.locator('input[inputmode="numeric"], input[autocomplete="one-time-code"]')
    await otpInputs.first().waitFor({ state: 'visible', timeout: 60_000 })
    const count = await otpInputs.count()
    if (count > 1) {
        const digits = code.split('')
        for (let i = 0; i < digits.length && i < count; i++) {
            await otpInputs.nth(i).fill(digits[i])
        }
    } else {
        await otpInputs.first().fill(code)
    }
    // Some Clerk configs auto-submit on the last digit; others need a click.
    const submit = ide.getByRole('button', { name: /^(Continue|Verify)/i })
    if (
        await submit
            .first()
            .isVisible()
            .catch(() => false)
    ) {
        await submit
            .first()
            .click()
            .catch(() => {})
    }
}

// Poll the reviewer review page until the run produces decryptable results (the
// results-key box appears) or the job errors / we time out. Re-navigates each
// poll because the review page caches its server data.
//
// Each poll ACTIVELY WAITS through the reload's render window rather than taking
// one instant isVisible() snapshot: a bare snapshot right after domcontentloaded
// routinely misses the SPA render (the box is there a moment later), so the loop
// would sleep a full interval and the results screen sits unnoticed for many
// seconds. We race the key box vs. the error text with a bounded waitFor so we
// react the instant either renders; a short sleep only spaces genuine retries.
async function waitForResults(ctx: RunContext, studyId: string): Promise<void> {
    const deadline = Date.now() + RESULTS_TIMEOUT_MS
    const keyBox = () => ctx.page.getByPlaceholder(RESULTS_KEY_PLACEHOLDER)
    const errored = () => ctx.page.getByText(/The code errored/i)
    while (Date.now() < deadline) {
        await gotoReview(ctx, studyId)
        // Wait out the render window (reload + SPA hydration + a margin) for
        // whichever terminal state appears first, instead of a single snapshot.
        await Promise.race([
            keyBox()
                .waitFor({ state: 'visible', timeout: RESULTS_RENDER_WAIT_MS })
                .catch(() => {}),
            errored()
                .waitFor({ state: 'visible', timeout: RESULTS_RENDER_WAIT_MS })
                .catch(() => {}),
        ])
        if (
            await keyBox()
                .isVisible()
                .catch(() => false)
        )
            return
        if (
            await errored()
                .isVisible()
                .catch(() => false)
        ) {
            throw new Error(`Study ${studyId} run ERRORED before producing results`)
        }
        await ctx.page.waitForTimeout(RESULTS_POLL_INTERVAL_MS)
    }
    throw new Error(
        `Timed out after ${RESULTS_TIMEOUT_MS / 60_000}min waiting for run results on study ${studyId}. ` +
            `The qa enclave runner may be slow or down — check ${ctx.baseURL}/${REVIEWER_ORG}/study/${studyId}/review`
    )
}
